### ISSUE TITLE
ValueError: Could not find function generate_path_profile in musette.models.

### ISSUE THREAD

**Issue by KhanMaytok** [mapeveri/django-musette#109]
I get this error when try `makemigrations`

`Please note that due to Python 2 limitations, you cannot serialize unbound method functions (e.g. a method declared and used in the same class body). Please move the function into the main module body to use migrations.`

**Comment by mapeveri** [comment]
What version of python and django do you use?

**Comment by KhanMaytok** [comment]
Python 2.7, Django 1.10.5

**Comment by KhanMaytok** [comment]
I find this possible solution.

https://stackoverflow.com/questions/25767787/django-cannot-create-migrations-for-imagefield-with-dynamic-upload-to-value

I will check it and submit a pull request if it works

**Comment by mapeveri** [comment]
Ok, anything I release a new version. Thanks!

**Comment by mapeveri** [comment]
I can not reproduce the error. After adding the application and configuring it, run python manage.py migrate and execute everything well.

**Comment by KhanMaytok** [comment]
Where should I put the `class Profile(AbstractProfile)` ?

I'm writting it and the models.py where are my `class User(AbstractUser)`

**Comment by mapeveri** [comment]
Check this app of example https://github.com/mapeveri/django-musette/tree/master/example

Check this file: https://github.com/mapeveri/django-musette/blob/master/example/main/models.py
