### ISSUE TITLE
Middleware error.

### ISSUE THREAD

**Issue by christianmtr** [mapeveri/django-musette#110]
Hi! I have [this error](https://gist.github.com/christianmtr/f90a5e9cbffd4eb18cc44263947bbd87) when I run runserver command.

I think that is because MIDDLEWARE_CLASSES setting is deprecated in Django version I'm using (1.10.5). But I'm not shure.

**Comment by mapeveri** [comment]
Hi, rare, because I try with django 1.11. If you change MIDDLEWARE_CLASSE tuple by MIDDLEWARE dict, follow the same error?.

**Comment by mapeveri** [comment]
I think I have to do this:

Https://stackoverflow.com/questions/42232606/django-exception-middleware-typeerror-object-takes-no-parameters

**Comment by christianmtr** [comment]
Yeah! I'm using MIDDLEWARE right now. I don't change to MIDDLEWARE_CLASSES because I have others apps in my project.

**Comment by christianmtr** [comment]
The solution from stackoverflow answer don't fix my problem, that shows the same error message.

**Comment by mapeveri** [comment]
I'll look at it and I'll let you know :)

**Comment by christianmtr** [comment]
Thanks!

**Comment by mapeveri** [comment]
Ready :)

Download the latest version of django-musette 0.3.1.
