### ISSUE TITLE
Default MCE config is overly complex

### ISSUE THREAD

**Issue by andybak** [mapeveri/django-musette#64]
I suggest that the out of the box experience should be to present a much more minimal WYSIWYG editor. There's also potentially security and vandalism issues with allowing such a wide range of tags and attributes.

**Comment by mapeveri** [comment]
@andybak Yes, you're right, in the next version I'm going to modify this. Thanks!

**Comment by mapeveri** [comment]
Now it looks like this. Configuration changed. It will be in the new release.

![image](https://cloud.githubusercontent.com/assets/6276555/21868592/455d5b0a-d832-11e6-9586-4da01342b6ab.png)

@andybak Thanks!
