### ISSUE TITLE
Same forum name with two different categories.

### ISSUE THREAD

**Issue by nikksbagul** [mapeveri/django-musette#68]
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "musette_forum_name_key"
DETAIL:  Key (name)=(Python) already exists.
```

**Comment by mapeveri** [comment]
like this:

**Comment by mapeveri** [comment]
It is not supported by the forum, but I will change the key to 'category + forum'. Like this:

http://stackoverflow.com/questions/16800375/how-can-set-two-field-primary-key-for-my-models-in-django

**Comment by mapeveri** [comment]
Ready. 

Will be in the next version.

**Comment by nikksbagul** [comment]
Now its give me error 

> get() returned more than one Forum -- it returned 2!

 on getting forum view.
```
/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/django_musette-0.2.5-py3.5.egg/musette/views.py in get

            forum = get_object_or_404(models.Forum, name=forum, hidden=False)
```

**Comment by mapeveri** [comment]
I look at it now

**Comment by mapeveri** [comment]
Check again please. Now the search is by 'category' + 'forum', but I had to change many things.

**Comment by mapeveri** [comment]
Release version 0.2.6 with this issue and more. Upgrade with pip.
