### ISSUE TITLE
Current status of user- Online or Offline

### ISSUE THREAD

**Issue by dikshajiwane** [mapeveri/django-musette#77]
If user is Offline then it changes the color from green to red and content is online. It would be better if it changes the content from Online to Offline. 
path:- django-musette/musette/templates/musette/users_forum.html
line no. 41-45
```
{% if us_pr.user.online %}
     <div class="label label-success"><b>Online</b></div>
{% else %}
    <div class="label label-danger"><b>Online</b></div>
{% endif %}
```
Same issue is in topic and other files where user's status is shown.

**Comment by mapeveri** [comment]
@dikshajiwane Hi, yes i agree.  I'm going to see it.

Thanks!

**Comment by mapeveri** [comment]
Ready.

Will be in the next version.

**Comment by dikshajiwane** [comment]
@mapeveri Thanks for quick response.
