### ISSUE TITLE
Like count is increasing by two on double click.

### ISSUE THREAD

**Issue by dikshajiwane** [mapeveri/django-musette#88]
While user likes a topic, its count is increased by two on double click and same thing happens for disliking a topic(its decreased by two). 
On continuous clicking its count increases and decreases randomly. Double click should be prevented.

**Comment by mapeveri** [comment]
@dikshajiwane I'm gonna check it.

Thanks!

**Comment by mapeveri** [comment]
Will be in the next version. Thanks!
